// COMPLETE GoHighLevel Notes Database - ALL STUDENTS
// Generated: 2026-03-20T14:17:00.000Z

// Coach mapping voor alle UserIDs
const COMPLETE_COACH_MAPPING = {
    'QVT1WQoi42eQHNevpiRL': 'Nabil',
    'jLMpKPPJNUc3HsHgBQX4': 'Nora',
    '7kYzWQljdJw495PGgf4a': 'Melvin',
    'bFJxyTSxKgHgx2EqVe9H': 'Melvin',
    '6zNaabgLvnwZWVwfOoS7': 'Coach #1',
    'N4eGG26wBxosATkCBnCD': 'Coach #2', 
    'vXkcrN7DRwV6KcYnz5Q1': 'Coach #3',
    null: 'Systeem',
    '': 'Systeem'
};

window.WOLF_PACK_NOTES_COMPLETE = {
  "Melissa Bos": [
    {"id":"9Q4wBxdkFKpuCiLlMjtB","body":"<p style=\"margin:0px; padding-left: 0px!important;\">Morgen om 11:00 uur voorstellen bij Niels de Widt, B2B. </p>","bodyText":"Morgen om 11:00 uur voorstellen bij Niels de Widt, B2B.","userId":"6zNaabgLvnwZWVwfOoS7","dateAdded":"2025-11-05T12:57:05.948Z","contactId":"0SwLAtokH9loZwrPCCOd","pinned":false,"businessId":"6925f4ead2662264a96203b1","relations":[{"objectKey":"opportunity","recordId":"ziz17DlMKDIDCUYCVWW0"},{"objectKey":"contact","recordId":"0SwLAtokH9loZwrPCCOd"}]},
  ],
  "Esther Van Antwerp": [
    {"id":"smCc4xYe4P5TBfCEfs5o","body":"<p style=\"margin:0px; padding-left: 0px!important;\">11/11/2025 Unboarding gehad met Esther, ze is moeder van twee kinderen. Ze woont in California samen met haar man die half Nederlands is. Ze is de FemalePack gejioned en zou daarop wachten totdat hij live is. Ze heeft wel al de eerste paar opdrachtjes gekregen en gaat daar mee aan de slag. Ze heeft al een beetje ervaring in de sales maar wilt nu echt gas gaan geven met het stukje closen</p>","bodyText":"11/11/2025 Unboarding gehad met Esther, ze is moeder van twee kinderen. Ze woont in California samen met haar man die half Nederlands is. Ze is de FemalePack gejioned en zou daarop wachten totdat hij live is. Ze heeft wel al de eerste paar opdrachtjes gekregen en gaat daar mee aan de slag. Ze heeft al een beetje ervaring in de sales maar wilt nu echt gas gaan geven met het stukje closen","userId":"bFJxyTSxKgHgx2EqVe9H","dateAdded":"2025-11-13T07:25:40.225Z","contactId":"940vPj6cirwnCyPRZ8PT","pinned":false,"relations":[{"objectKey":"opportunity","recordId":"2KXDj4Lohf5zGxQLz9oh"},{"objectKey":"contact","recordId":"940vPj6cirwnCyPRZ8PT"}]},
  ],
  "Jim@launchmyagents.ai Koning": [
    {"id":"PHrxkw7X04cKynNXxBpA","body":"https://fathom.video/share/PhV14PfkkF7p_r6yPXhi6Z_HDsFJ14x2","bodyText":"https://fathom.video/share/PhV14PfkkF7p_r6yPXhi6Z_HDsFJ14x2","userId":null,"dateAdded":"2026-02-23T13:49:57.750Z","contactId":"Be2mNSuSq6mi3hC3f1Tf","pinned":false,"relations":[]},
    {"id":"XKdlpV54jyngKFmHSYBV","body":"<p style=\"margin:0px; padding-left: 0px!important;\">goeie call met Jim gehad, heeft een agency waarin hij bedrijven ontzorgt met AI, laat veel sales liggen op het moment en wilt graag dat wij hem Helpen met een closer te plaatsen. Heb hem overgedragen aan Maurice</p>","bodyText":"goeie call met Jim gehad, heeft een agency waarin hij bedrijven ontzorgt met AI, laat veel sales liggen op het moment en wilt graag dat wij hem Helpen met een closer te plaatsen. Heb hem overgedragen aan Maurice","userId":"vXkcrN7DRwV6KcYnz5Q1","dateAdded":"2026-01-30T10:24:15.484Z","contactId":"Be2mNSuSq6mi3hC3f1Tf","pinned":false,"relations":[{"objectKey":"opportunity","recordId":"TyhSQnyC9t5efZzv79jk"},{"objectKey":"contact","recordId":"Be2mNSuSq6mi3hC3f1Tf"}]},
  ],
  "Imran Aslam": [
    {"id":"sROCjuUomjkuZdNEkIOi","body":"<p style=\"margin:0px; padding-left: 0px!important;\">aantal calls/belletjes gehad met Imran, hij is aan het closen bij Yssine AKA Elite club. ondertussen stuurt hij me zijn calls door reviews. we gaan werken naar examinering vanaf nu</p>","bodyText":"aantal calls/belletjes gehad met Imran, hij is aan het closen bij Yssine AKA Elite club. ondertussen stuurt hij me zijn calls door reviews. we gaan werken naar examinering vanaf nu","userId":"QVT1WQoi42eQHNevpiRL","dateAdded":"2026-02-04T14:16:51.743Z","contactId":"BgyLrrEh7mohM9qTr9yq","pinned":false,"relations":[{"objectKey":"opportunity","recordId":"yt7fGpEWF0EMNfdaEl8j"},{"objectKey":"contact","recordId":"BgyLrrEh7mohM9qTr9yq"}]},
    {"id":"DiBqRC7LGvdbj4zXougU","body":"<p style=\"margin:0px; padding-left: 0px!important;\">1e call gehad met lotfi, hij heeft heel erg zijn eigen manier van sales en daarom op gehamerd dat dat eruit moet. hij is bezig rollenspellen en pakt het goed op</p>","bodyText":"1e call gehad met lotfi, hij heeft heel erg zijn eigen manier van sales en daarom op gehamerd dat dat eruit moet. hij is bezig rollenspellen en pakt het goed op","userId":"QVT1WQoi42eQHNevpiRL","dateAdded":"2026-01-08T15:53:14.500Z","contactId":"BgyLrrEh7mohM9qTr9yq","pinned":false,"relations":[{"objectKey":"opportunity","recordId":"yt7fGpEWF0EMNfdaEl8j"},{"objectKey":"contact","recordId":"BgyLrrEh7mohM9qTr9yq"}]},
    {"id":"OelwtyVqXOYBFZQc9QYU","body":"<p style=\"margin:0px; padding-left: 0px!important;\">29/11/2025: unboarding gehad met Imran. Man van 31, hij kent Lotfi en is via hem binnen gekomen. Die twee waren collega's , hij is verantwoordelijke van een consultansy bureau. Heeft een hele team onder zich, hij vind het wel leuk werk. Alleen mist de vrijheid heel erg. Het is een man met al ruim 8/9 jaar ervaring in de sales. Hij is heel slim en heeft veel kennis. Hij gaat in februari met zn vriendin naar Korea 8 maanden en wilt het liefst daarvoor al de curcus afgerond hebben. Sam is z'n coach, ik heb zn nummer gestuurd dus die zal contact met hem opnemen!</p>","bodyText":"29/11/2025: unboarding gehad met Imran. Man van 31, hij kent Lotfi en is via hem binnen gekomen. Die twee waren collega's , hij is verantwoordelijke van een consultansy bureau. Heeft een hele team onder zich, hij vind het wel leuk werk. Alleen mist de vrijheid heel erg. Het is een man met al ruim 8/9 jaar ervaring in de sales. Hij is heel slim en heeft veel kennis. Hij gaat in februari met zn vriendin naar Korea 8 maanden en wilt het liefst daarvoor al de curcus afgerond hebben. Sam is z'n coach, ik heb zn nummer gestuurd dus die zal contact met hem opnemen!","userId":"bFJxyTSxKgHgx2EqVe9H","dateAdded":"2025-12-01T08:48:18.076Z","contactId":"BgyLrrEh7mohM9qTr9yq","pinned":false,"relations":[{"objectKey":"opportunity","recordId":"yt7fGpEWF0EMNfdaEl8j"},{"objectKey":"contact","recordId":"BgyLrrEh7mohM9qTr9yq"}]},
  ],
  "Alen Arnotovic": [
    {"id":"4JNjngAz904DwNbY5xFD","body":"Met Alain gezeten. Alain heeft het script nu helemaal door. Dus hij mag nu de objections gaan oefenen. Ik heb alle objections met hem weerlegd. Hij gaat de call terugkijken en vervolgens gaat hij er een lijst van maken en alle objections opschrijven. En dat is helemaal uitwerken.","bodyText":"Met Alain gezeten. Alain heeft het script nu helemaal door. Dus hij mag nu de objections gaan oefenen. Ik heb alle objections met hem weerlegd. Hij gaat de call terugkijken en vervolgens gaat hij er een lijst van maken en alle objections opschrijven. En dat is helemaal uitwerken.","userId":"7kYzWQljdJw495PGgf4a","dateAdded":"2025-10-17T12:39:09.366Z","contactId":"OawpaYRt3HmOGa2CKPcb","pinned":false,"relations":[{"objectKey":"opportunity","recordId":"VYbjNBPw3cyAwoWljzN4"},{"objectKey":"contact","recordId":"OawpaYRt3HmOGa2CKPcb"}]},
  ],
  "Joost Lievense": [
    {"id":"5AP5dP3V1f01vVlxEHCH","body":"<p style=\"margin:0px; padding-left: 0px!important;\">Geplaatst bij AgenciYou. </p>","bodyText":"Geplaatst bij AgenciYou.","userId":"6zNaabgLvnwZWVwfOoS7","dateAdded":"2025-11-05T12:56:44.547Z","contactId":"QeNBF7xDviuPqiEbXHY2","pinned":false,"businessId":"6925f558d2662264a96203f7","relations":[{"objectKey":"opportunity","recordId":"9qy176TraeS5harm944R"},{"objectKey":"contact","recordId":"QeNBF7xDviuPqiEbXHY2"}]},
  ],
  "Wilco Mikic": [
    {"id":"jDLpbufP4FqaxZofdrcx","body":"<p style=\"margin:0px; padding-left: 0px!important;\">Vandaag samen met Melvin weer een call gehad met de DMU van De Duurzame Jongens. Na een call van bijna 2 uur hebben we mondeling akkoord gekregen. Nu gaan we aanstaande vrijdag 16:00 een call met Mylene doen (CFO) om alles te regelen omtrent performance fee (0-meting), eerste betaling van €16.667,-. Voor die meeting moeten Melvin &amp; ik de overeenkomst gestuurd hebben.</p>","bodyText":"Vandaag samen met Melvin weer een call gehad met de DMU van De Duurzame Jongens. Na een call van bijna 2 uur hebben we mondeling akkoord gekregen. Nu gaan we aanstaande vrijdag 16:00 een call met Mylene doen (CFO) om alles te regelen omtrent performance fee (0-meting), eerste betaling van €16.667,-. Voor die meeting moeten Melvin & ik de overeenkomst gestuurd hebben.","userId":"vXkcrN7DRwV6KcYnz5Q1","dateAdded":"2026-02-11T16:10:19.508Z","contactId":"UipYi0Da0lCR2hEOWKfc","pinned":false,"relations":[{"objectKey":"opportunity","recordId":"XydTgQHWuaFqHaVZWCwY"},{"objectKey":"contact","recordId":"UipYi0Da0lCR2hEOWKfc"}]},
    {"id":"OtIfI3tojfiD4SzRHXUi","body":"<p style=\"margin:0px; padding-left: 0px!important;\">Wilco is general manager bij De duurzame Jongens, ik had de eerste call met hem en identificeerde direct dat er veel te halen viel toen hij aangaf dat hij 12 miljoen aan openstaande orders had en daar niks van geclosed was door een niet goed opererend salesteam. Direct melvin bij me geroepen om een plan te bespreken. We gaan hun hele salesfunnel bekijken en verbeteren om de conversie te verhogen, hebben nu al 3 gesprekken gehad en hebben aanstaande woensdag om 14:00 CET het definitieve gesprek om ervoor te zorgen dat ze geclosed worden. Bij het laatste gesprek hebben wij een aanbod gedaan om 5% conversieverhoging te realiseren voor in totaal €99.000 verdeeld over 3 maanden. Dit vonden zij iets te hoog en willen graag risico spreiding, nu gaan we een aanbod doen om die 5% te realiseren voor €50.000 verdeeld over 3 maanden met een performance fee van €10.000 per extra gerealiseerd conversie percentage. We moeten nog wel wat verzinnen op wat als we de 5% niet realiseren, hiervoor gaan melvin en ik aanstaande dinsdag over in gesprek en dit goed uitspitten zodat we met een offer komen wat zij niet kunnen weerstaan, daarnaast moeten we ook de andere mogelijkheden bespreken zoals; eventueel een salesmanager op locatie, plaatsen van extra closers indien nodig bij schaalbaarheid, etc.</p>","bodyText":"Wilco is general manager bij De duurzame Jongens, ik had de eerste call met hem en identificeerde direct dat er veel te halen viel toen hij aangaf dat hij 12 miljoen aan openstaande orders had en daar niks van geclosed was door een niet goed opererend salesteam. Direct melvin bij me geroepen om een plan te bespreken. We gaan hun hele salesfunnel bekijken en verbeteren om de conversie te verhogen, hebben nu al 3 gesprekken gehad en hebben aanstaande woensdag om 14:00 CET het definitieve gesprek om ervoor te zorgen dat ze geclosed worden. Bij het laatste gesprek hebben wij een aanbod gedaan om 5% conversieverhoging te realiseren voor in totaal €99.000 verdeeld over 3 maanden. Dit vonden zij iets te hoog en willen graag risico spreiding, nu gaan we een aanbod doen om die 5% te realiseren voor €50.000 verdeeld over 3 maanden met een performance fee van €10.000 per extra gerealiseerd conversie percentage. We moeten nog wel wat verzinnen op wat als we de 5% niet realiseren, hiervoor gaan melvin en ik aanstaande dinsdag over in gesprek en dit goed uitspitten zodat we met een offer komen wat zij niet kunnen weerstaan, daarnaast moeten we ook de andere mogelijkheden bespreken zoals; eventueel een salesmanager op locatie, plaatsen van extra closers indien nodig bij schaalbaarheid, etc.","userId":"vXkcrN7DRwV6KcYnz5Q1","dateAdded":"2026-01-31T17:55:56.849Z","contactId":"UipYi0Da0lCR2hEOWKfc","pinned":false,"relations":[{"objectKey":"opportunity","recordId":"XydTgQHWuaFqHaVZWCwY"},{"objectKey":"contact","recordId":"UipYi0Da0lCR2hEOWKfc"}]},
  ],
  "Len Gerards": [
    {"id":"beO3PvOYGoFGjvHb6Xzn","body":"<p style=\"margin:0px; padding-left: 0px!important;\">31-12-2025(Lorenzo): Passed his exam! 2e keer LFG</p>","bodyText":"31-12-2025(Lorenzo): Passed his exam! 2e keer LFG","userId":"N4eGG26wBxosATkCBnCD","dateAdded":"2025-12-31T12:51:43.708Z","contactId":"aShf3piae5UUnMaz4zqa","pinned":false,"relations":[{"recordId":"cD0d0LpHS2FsID1kLvaq","objectKey":"opportunity"},{"objectKey":"contact","recordId":"aShf3piae5UUnMaz4zqa"}]},
    {"id":"4MeScl04TlOGqtQ7e97i","body":"<p style=\"margin:0px; padding-left: 0px!important;\">24-12-2025 (Lorenzo): 23e niet geslaagd, gaat nu opnieuw de schoolbank in en opnieuw oefenen. Zat te veel door elkaar in het frame work en stelde niet de juiste diepgaande vragen. </p>","bodyText":"24-12-2025 (Lorenzo): 23e niet geslaagd, gaat nu opnieuw de schoolbank in en opnieuw oefenen. Zat te veel door elkaar in het frame work en stelde niet de juiste diepgaande vragen.","userId":"N4eGG26wBxosATkCBnCD","dateAdded":"2025-12-24T13:25:39.194Z","contactId":"aShf3piae5UUnMaz4zqa","pinned":false,"relations":[{"recordId":"cD0d0LpHS2FsID1kLvaq","objectKey":"opportunity"},{"recordId":"aShf3piae5UUnMaz4zqa","objectKey":"contact"}]},
  ],
  "Kyle Dowling": [
    {"id":"PJXjLZc04uNS7NO6pMgk","body":"https://fathom.video/share/4p_29VmRciR3PnGoRy68ZFpzE3NSHwQu","bodyText":"https://fathom.video/share/4p_29VmRciR3PnGoRy68ZFpzE3NSHwQu","userId":null,"dateAdded":"2026-02-11T18:52:50.502Z","contactId":"g7nanpTQzOd0ZsJCvW8I","pinned":false,"relations":[]},
    {"id":"97FNraUhuWfOjquUEu4Z","body":"<p style=\"margin:0px; padding-left: 0px!important;\">02/02/2026: Net onboarding gehad met Kyle, echt een super leuke en lieve guy. 23 jaar oud en woont in Amerika. Hij had Melvin ontmoet in Miami, ze raakte aan de praat en Kyle wist gelijk dat dit zijn pad was. Als werk rijd hij op een vrachtwagen en maakt hij lange dagen. Hij was altijd al geintresseerd in sales en daarom kan hij ook niet wachten om te starten. Hij is nu al super dankbaar voor deze kans. Ik heb hem gekoppeld aan Eray, die heeft zn nummer en neemt het vanaf hier over</p>","bodyText":"02/02/2026: Net onboarding gehad met Kyle, echt een super leuke en lieve guy. 23 jaar oud en woont in Amerika. Hij had Melvin ontmoet in Miami, ze raakte aan de praat en Kyle wist gelijk dat dit zijn pad was. Als werk rijd hij op een vrachtwagen en maakt hij lange dagen. Hij was altijd al geintresseerd in sales en daarom kan hij ook niet wachten om te starten. Hij is nu al super dankbaar voor deze kans. Ik heb hem gekoppeld aan Eray, die heeft zn nummer en neemt het vanaf hier over","userId":"bFJxyTSxKgHgx2EqVe9H","dateAdded":"2026-02-02T18:47:58.059Z","contactId":"g7nanpTQzOd0ZsJCvW8I","pinned":false,"relations":[{"objectKey":"opportunity","recordId":"2A7bn9X88ZqqjA02LjDf"},{"objectKey":"contact","recordId":"g7nanpTQzOd0ZsJCvW8I"}]},
  ],
  "Karl Addy Barandagiye": [
    {"id":"sII8Neq1qTix96fBV0oA","body":"<p style=\"margin:0px; padding-left: 0px!important;\">29/11/2025: Ook unboarding gehad met Imran. Man van 31, hij kent Lotfi en is via hem binnen gekomen. Die twee waren collega's , hij is verantwoordelijke van een consultansy bureau. Heeft een hele team onder zich, hij vind het wel leuk werk. Alleen mist de vrijheid heel erg. Het is een man met al ruim 8/9 jaar ervaring in de sales. Hij is heel slim en heeft veel kennis. Hij gaat in februari met zn vriendin naar Korea 8 maanden en wilt het liefst daarvoor al de curcus afgerond hebben. Sam is z'n coach, ik heb zn nummer gestuurd dus die zal contact met hem opnemen!</p>","bodyText":"29/11/2025: Ook unboarding gehad met Imran. Man van 31, hij kent Lotfi en is via hem binnen gekomen. Die twee waren collega's , hij is verantwoordelijke van een consultansy bureau. Heeft een hele team onder zich, hij vind het wel leuk werk. Alleen mist de vrijheid heel erg. Het is een man met al ruim 8/9 jaar ervaring in de sales. Hij is heel slim en heeft veel kennis. Hij gaat in februari met zn vriendin naar Korea 8 maanden en wilt het liefst daarvoor al de curcus afgerond hebben. Sam is z'n coach, ik heb zn nummer gestuurd dus die zal contact met hem opnemen!","userId":"bFJxyTSxKgHgx2EqVe9H","dateAdded":"2025-11-29T10:56:06.177Z","contactId":"njG2TCfXzFF37Ylvpjy4","pinned":false,"relations":[{"objectKey":"opportunity","recordId":"eUlmCOIYD2B9GCYPfvKn"},{"objectKey":"contact","recordId":"njG2TCfXzFF37Ylvpjy4"}]},
  ],
  "Branco Van Peer": [
    {"id":"JsNq8tpQ1ktqWYRwJPYb","body":"<p style=\"margin:0px; padding-left: 0px!important;\">Was eerder gestopt met coaching, te druk thuis, vrouw etc etc. Heb het nu weer met hem samen opgepakt vanaf W3, the Golden Script volledig doorgenomen. Gaan het nu weer oppakken en gas geven, lijkt weer gemotiveerd te zijn en wilt echt knallen. Is echt een slimme gast, snapt het goed en neemt de stof ook goed en snel tot zichzelf op. </p>","bodyText":"Was eerder gestopt met coaching, te druk thuis, vrouw etc etc. Heb het nu weer met hem samen opgepakt vanaf W3, the Golden Script volledig doorgenomen. Gaan het nu weer oppakken en gas geven, lijkt weer gemotiveerd te zijn en wilt echt knallen. Is echt een slimme gast, snapt het goed en neemt de stof ook goed en snel tot zichzelf op.","userId":"6zNaabgLvnwZWVwfOoS7","dateAdded":"2025-11-25T17:01:12.513Z","contactId":"xQiEjmNT4eD2pWv5bw0u","pinned":false,"relations":[{"objectKey":"opportunity","recordId":"zOvDAVlFeqk2cwyo32lI"},{"objectKey":"contact","recordId":"xQiEjmNT4eD2pWv5bw0u"}]},
  ],
};
